"""Replace broken old handler section with corrected versions."""
path = r"D:\by\polap-db\services\voltnuerongridd\src\main.rs"
with open(path, "r", encoding="utf-8") as f:
    content = f.read()

OLD_START = "3-WS1-05: Parse a simple WHERE clause string into vectorized filter predicates.\n"
OLD_END_MARKER = "\nfn evaluate_deadlock_scan_outcome("

idx_start = content.find(OLD_START)
idx_end   = content.find(OLD_END_MARKER, idx_start)

if idx_start == -1 or idx_end == -1:
    print("ERROR: markers not found", idx_start, idx_end)
    exit(1)

old_section = content[idx_start : idx_end + len(OLD_END_MARKER)]
print(f"Replacing {len(old_section)} chars")

NEW_SECTION = (
    "/// S3-WS1-05: parse a WHERE clause string into `VectorizedFilter` predicates.\n"
    "/// Handles simple `col op val` expressions joined by ` AND `.\n"
    "fn parse_where_predicates(\n"
    "    where_clause: &str,\n"
    ") -> Option<Vec<voltnuerongrid_store::columnar::VectorizedFilter>> {\n"
    "    use voltnuerongrid_store::columnar::{FilterOp, VectorizedFilter};\n"
    "    let preds: Vec<VectorizedFilter> = where_clause\n"
    "        .split(\" AND \")\n"
    "        .filter_map(|clause| {\n"
    "            let clause = clause.trim();\n"
    "            let ops: &[(&str, FilterOp)] = &[\n"
    "                (\">=\", FilterOp::Gte),\n"
    "                (\"<=\", FilterOp::Lte),\n"
    "                (\"!=\", FilterOp::Ne),\n"
    "                (\">\",  FilterOp::Gt),\n"
    "                (\"<\",  FilterOp::Lt),\n"
    "                (\"=\",  FilterOp::Eq),\n"
    "            ];\n"
    "            for (sym, op) in ops {\n"
    "                if let Some(pos) = clause.find(sym) {\n"
    "                    let col = clause[..pos].trim().to_string();\n"
    "                    let val = clause[pos + sym.len()..].trim()\n"
    "                        .trim_matches('\\'').trim_matches('\"').to_string();\n"
    "                    if !col.is_empty() {\n"
    "                        return Some(VectorizedFilter { column: col, op: op.clone(), value: val });\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "            None\n"
    "        })\n"
    "        .collect();\n"
    "    if preds.is_empty() { None } else { Some(preds) }\n"
    "}\n"
    "\n"
    "// \u2500\u2500\u2500 S2-WS2-02: WAL durability + recovery handlers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "\n"
    "/// S2-WS2-02: return WAL engine stats.\n"
    "async fn wal_status(State(state): State<AppState>) -> impl axum::response::IntoResponse {\n"
    "    use axum::{Json as AJ, http::StatusCode};\n"
    "    let wal = state.wal_engine.lock().expect(\"wal_engine lock\");\n"
    "    let records = wal.wal_records();\n"
    "    let wal_len = records.len();\n"
    "    let latest_seq = records.last().map(|r| r.sequence).unwrap_or(0);\n"
    "    let checkpoint_count = wal.checkpoint_count();\n"
    "    drop(wal);\n"
    "    (StatusCode::OK, AJ(WalStatusResponse {\n"
    "        status: \"ok\",\n"
    "        wal_len,\n"
    "        latest_sequence: latest_seq,\n"
    "        checkpoint_count,\n"
    "    }))\n"
    "}\n"
    "\n"
    "/// S2-WS2-02: replay WAL records into the row store (or dry-run).\n"
    "async fn wal_recover(\n"
    "    State(state): State<AppState>,\n"
    "    axum::extract::Json(req): axum::extract::Json<WalRecoverRequest>,\n"
    ") -> impl axum::response::IntoResponse {\n"
    "    use axum::{Json as AJ, http::StatusCode};\n"
    "    let dry_run = req.dry_run.unwrap_or(false);\n"
    "    let wal = state.wal_engine.lock().expect(\"wal_engine lock\");\n"
    "    let records = wal.wal_records().to_vec();\n"
    "    drop(wal);\n"
    "    let mut replayed: usize = 0;\n"
    "    if !dry_run {\n"
    "        let mut rs = state.row_store.lock().expect(\"row_store lock wal_recover\");\n"
    "        let xid = rs.begin_xid();\n"
    "        for rec in &records {\n"
    "            if rec.value == \"__deleted__\" {\n"
    "                rs.delete(xid, &rec.key);\n"
    "            } else {\n"
    "                let data: std::collections::HashMap<String, String> =\n"
    "                    serde_json::from_str(&rec.value)\n"
    "                        .unwrap_or_else(|_| [(\"_raw\".to_string(), rec.value.clone())]\n"
    "                            .into_iter().collect());\n"
    "                rs.insert(xid, &rec.key, data);\n"
    "            }\n"
    "            replayed += 1;\n"
    "        }\n"
    "    } else {\n"
    "        replayed = records.len();\n"
    "    }\n"
    "    (StatusCode::OK, AJ(WalRecoverResponse {\n"
    "        status: \"ok\",\n"
    "        records_replayed: replayed,\n"
    "        dry_run,\n"
    "    }))\n"
    "}\n"
    "\n"
    "// \u2500\u2500\u2500 S7-WS6-04: Chaos/game-day injection handlers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "\n"
    "fn now_epoch_ms_chaos() -> u64 {\n"
    "    std::time::SystemTime::now()\n"
    "        .duration_since(std::time::UNIX_EPOCH)\n"
    "        .unwrap_or_default()\n"
    "        .as_millis() as u64\n"
    "}\n"
    "\n"
    "/// S7-WS6-04: inject a chaos/game-day fault event.\n"
    "async fn chaos_inject(\n"
    "    State(state): State<AppState>,\n"
    "    axum::extract::Json(req): axum::extract::Json<ChaosInjectRequest>,\n"
    ") -> impl axum::response::IntoResponse {\n"
    "    use axum::{Json as AJ, http::StatusCode};\n"
    "    let event = ChaosEvent {\n"
    "        fault_type: req.fault_type,\n"
    "        target_node: req.target_node,\n"
    "        parameters: req.parameters,\n"
    "        injected_at_ms: now_epoch_ms_chaos(),\n"
    "        cleared_at_ms: None,\n"
    "    };\n"
    "    let mut cs = state.chaos_state.lock().expect(\"chaos_state lock\");\n"
    "    cs.active_faults.push(event);\n"
    "    let count = cs.active_faults.len();\n"
    "    drop(cs);\n"
    "    (StatusCode::OK, AJ(serde_json::json!({ \"status\": \"injected\", \"active_fault_count\": count })))\n"
    "}\n"
    "\n"
    "/// S7-WS6-04: clear all active faults; move them to history.\n"
    "async fn chaos_clear(State(state): State<AppState>) -> impl axum::response::IntoResponse {\n"
    "    use axum::{Json as AJ, http::StatusCode};\n"
    "    let cleared_at = now_epoch_ms_chaos();\n"
    "    let mut cs = state.chaos_state.lock().expect(\"chaos_state lock\");\n"
    "    let mut cleared: Vec<ChaosEvent> = cs.active_faults.drain(..).map(|mut e| {\n"
    "        e.cleared_at_ms = Some(cleared_at);\n"
    "        e\n"
    "    }).collect();\n"
    "    cs.event_history.append(&mut cleared);\n"
    "    let history_len = cs.event_history.len();\n"
    "    drop(cs);\n"
    "    (StatusCode::OK, AJ(serde_json::json!({ \"status\": \"cleared\", \"history_len\": history_len })))\n"
    "}\n"
    "\n"
    "/// S7-WS6-04: return current chaos state summary.\n"
    "async fn chaos_status(State(state): State<AppState>) -> impl axum::response::IntoResponse {\n"
    "    use axum::{Json as AJ, http::StatusCode};\n"
    "    let cs = state.chaos_state.lock().expect(\"chaos_state lock\");\n"
    "    let active_fault_count = cs.active_faults.len();\n"
    "    let total_injected = cs.active_faults.len() + cs.event_history.len();\n"
    "    let active_faults = cs.active_faults.clone();\n"
    "    drop(cs);\n"
    "    (StatusCode::OK, AJ(ChaosStatusResponse {\n"
    "        status: \"ok\",\n"
    "        active_fault_count,\n"
    "        total_injected,\n"
    "        active_faults,\n"
    "    }))\n"
    "}\n"
    "\n"
    "fn evaluate_deadlock_scan_outcome("
)

assert old_section in content, "ASSERT FAILED: old section not in content"
content = content.replace(old_section, NEW_SECTION, 1)

with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done - handler replacement complete")
