$f = 'd:\by\polap-db\services\voltnuerongridd\src\main.rs'
$s = [IO.File]::ReadAllText($f)
$crlf = "`r`n"

# Fix rows_field_count handler
$old = "async fn rows_field_count(" + $crlf + "    State(state): State<Arc<AppState>>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<Json<RowsFieldCountResponse>, (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let snapshot = state.row_store.lock().expect("row_store lock rows_field_count").export_rows_snapshot();' + $crlf + "    let row_count = snapshot.len();" + $crlf + '    let total_fields = snapshot.values().map(|r| r.len()).sum::<usize>();' + $crlf + '    Ok(Json(RowsFieldCountResponse { status: "ok", total_fields, row_count }))' + $crlf + "}"
$new = "async fn rows_field_count(" + $crlf + "    State(state): State<AppState>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<(StatusCode, Json<RowsFieldCountResponse>), (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let rs = state.row_store.lock().expect("row_store lock rows_field_count");' + $crlf + "    let snapshot = rs.export_rows_snapshot();" + $crlf + "    drop(rs);" + $crlf + "    let row_count = snapshot.len();" + $crlf + "    let total_fields: usize = snapshot.iter().map(|(_, p)| p.len()).sum();" + $crlf + '    Ok((StatusCode::OK, Json(RowsFieldCountResponse { status: "ok", total_fields, row_count })))' + $crlf + "}"
if ($s.Contains($old)) { $s = $s.Replace($old, $new); Write-Host "HANDLER1 OK" } else { Write-Host "HANDLER1 FAIL"; exit 1 }

# Fix wal_entry_latest handler
$old2 = "async fn wal_entry_latest(" + $crlf + "    State(state): State<Arc<AppState>>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<Json<WalEntryLatestResponse>, (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let records = state.wal_engine.lock().expect("wal_engine lock wal_entry_latest").wal_records();' + $crlf + "    let entry_sequence = records.last().map(|r| r.sequence).unwrap_or(0);" + $crlf + "    let has_entry = !records.is_empty();" + $crlf + '    Ok(Json(WalEntryLatestResponse { status: "ok", has_entry, entry_sequence }))' + $crlf + "}"
$new2 = "async fn wal_entry_latest(" + $crlf + "    State(state): State<AppState>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<(StatusCode, Json<WalEntryLatestResponse>), (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let wal = state.wal_engine.lock().expect("wal_engine lock wal_entry_latest");' + $crlf + "    let records = wal.wal_records();" + $crlf + "    let entry_sequence = records.last().map(|r| r.sequence).unwrap_or(0);" + $crlf + "    let has_entry = !records.is_empty();" + $crlf + "    drop(wal);" + $crlf + '    Ok((StatusCode::OK, Json(WalEntryLatestResponse { status: "ok", has_entry, entry_sequence })))' + $crlf + "}"
if ($s.Contains($old2)) { $s = $s.Replace($old2, $new2); Write-Host "HANDLER2 OK" } else { Write-Host "HANDLER2 FAIL"; exit 1 }

[IO.File]::WriteAllText($f, $s)
Write-Host "Done. Lines:" ($s.Split("`n").Count)
