$f = 'd:\by\polap-db\services\voltnuerongridd\src\main.rs'
$s = [IO.File]::ReadAllText($f)
$crlf = "`r`n"

Write-Host "Initial lines:" ($s.Split("`n").Count)

# 1. Structs after WalFlushCountResponse
# Use a unique but simple anchor that avoids box-drawing chars
$old1 = "struct WalFlushCountResponse {" + $crlf + "    status: &'static str," + $crlf + "    flush_count: usize," + $crlf + "}" + $crlf
$new1 = "struct WalFlushCountResponse {" + $crlf + "    status: &'static str," + $crlf + "    flush_count: usize," + $crlf + "}" + $crlf + $crlf + "// S3-WS1-28: rows/field/count + wal/entry/latest structs" + $crlf + $crlf + "#[derive(Debug, Serialize)]" + $crlf + "struct RowsFieldCountResponse {" + $crlf + "    status: &'static str," + $crlf + "    total_fields: usize," + $crlf + "    row_count: usize," + $crlf + "}" + $crlf + $crlf + "#[derive(Debug, Serialize)]" + $crlf + "struct WalEntryLatestResponse {" + $crlf + "    status: &'static str," + $crlf + "    has_entry: bool," + $crlf + "    entry_sequence: u64," + $crlf + "}" + $crlf
if ($s.Contains($old1)) { $s = $s.Replace($old1, $new1); Write-Host "1 STRUCT OK" } else { Write-Host "1 STRUCT FAIL" }

# 2. Routes after wal/flush/count
$old2 = '        .route("/api/v1/store/wal/flush/count", get(wal_flush_count))' + $crlf + '        // S11-WS1-19'
$new2 = '        .route("/api/v1/store/wal/flush/count", get(wal_flush_count))' + $crlf + '        // S3-WS1-28: rows/field/count + wal/entry/latest' + $crlf + '        .route("/api/v1/store/rows/field/count", get(rows_field_count))' + $crlf + '        .route("/api/v1/store/wal/entry/latest", get(wal_entry_latest))' + $crlf + '        // S11-WS1-19'
if ($s.Contains($old2)) { $s = $s.Replace($old2, $new2); Write-Host "2 ROUTES OK" } else { Write-Host "2 ROUTES FAIL" }

# 3. Handlers: anchor on unique fn signature
$old3 = "/// S7-WS6-01: Return accumulated vote grant/reject counts"
$new3 = "// S3-WS1-28: rows/field/count endpoint" + $crlf + "async fn rows_field_count(" + $crlf + "    State(state): State<Arc<AppState>>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<Json<RowsFieldCountResponse>, (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let snapshot = state.row_store.lock().expect("row_store lock rows_field_count").export_rows_snapshot();' + $crlf + "    let row_count = snapshot.len();" + $crlf + "    let total_fields = snapshot.values().map(|r| r.len()).sum::<usize>();" + $crlf + '    Ok(Json(RowsFieldCountResponse { status: "ok", total_fields, row_count }))' + $crlf + "}" + $crlf + $crlf + "// S3-WS1-28: wal/entry/latest endpoint" + $crlf + "async fn wal_entry_latest(" + $crlf + "    State(state): State<Arc<AppState>>," + $crlf + "    headers: HeaderMap," + $crlf + ") -> Result<Json<WalEntryLatestResponse>, (StatusCode, Json<AuthErrorResponse>)> {" + $crlf + "    require_operator_auth(&headers, &state)?;" + $crlf + '    let records = state.wal_engine.lock().expect("wal_engine lock wal_entry_latest").wal_records();' + $crlf + "    let entry_sequence = records.last().map(|r| r.sequence).unwrap_or(0);" + $crlf + "    let has_entry = !records.is_empty();" + $crlf + '    Ok(Json(WalEntryLatestResponse { status: "ok", has_entry, entry_sequence }))' + $crlf + "}" + $crlf + $crlf + "/// S7-WS6-01: Return accumulated vote grant/reject counts"
if ($s.Contains($old3)) { $s = $s.Replace($old3, $new3); Write-Host "3 HANDLERS OK" } else { Write-Host "3 HANDLERS FAIL" }

# 4. Tests: anchor on unique closing of last test + mod close
$old4 = "        assert!(result.is_err());" + $crlf + "        assert_eq!(result.unwrap_err().0, StatusCode::UNAUTHORIZED);" + $crlf + "    }" + $crlf + $crlf + "}"
$new4 = "        assert!(result.is_err());" + $crlf + "        assert_eq!(result.unwrap_err().0, StatusCode::UNAUTHORIZED);" + $crlf + "    }" + $crlf + $crlf + "    // S3-WS1-28: rows_field_count tests" + $crlf + $crlf + "    #[tokio::test]" + $crlf + "    async fn s11_ws1_28_rows_field_count_ok() {" + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = operator_headers("test-key", "admin");' + $crlf + "        let res = rows_field_count(State(state), hdrs).await;" + $crlf + '        assert!(res.is_ok(), "rows_field_count should return ok");' + $crlf + "        let body = res.unwrap().0;" + $crlf + '        assert_eq!(body.status, "ok");' + $crlf + "    }" + $crlf + $crlf + "    #[tokio::test]" + $crlf + "    async fn s11_ws1_28_rows_field_count_missing_auth() {" + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + "        let hdrs = HeaderMap::new();" + $crlf + "        let res = rows_field_count(State(state), hdrs).await;" + $crlf + '        assert!(res.is_err(), "missing auth should be rejected");' + $crlf + "        assert_eq!(res.unwrap_err().0, StatusCode::UNAUTHORIZED);" + $crlf + "    }" + $crlf + $crlf + "    // S3-WS1-28: wal_entry_latest tests" + $crlf + $crlf + "    #[tokio::test]" + $crlf + "    async fn s11_ws1_28_wal_entry_latest_ok() {" + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = operator_headers("test-key", "admin");' + $crlf + "        let res = wal_entry_latest(State(state), hdrs).await;" + $crlf + '        assert!(res.is_ok(), "wal_entry_latest should return ok");' + $crlf + "        let body = res.unwrap().0;" + $crlf + '        assert_eq!(body.status, "ok");' + $crlf + "    }" + $crlf + $crlf + "    #[tokio::test]" + $crlf + "    async fn s11_ws1_28_wal_entry_latest_missing_auth() {" + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + "        let hdrs = HeaderMap::new();" + $crlf + "        let res = wal_entry_latest(State(state), hdrs).await;" + $crlf + '        assert!(res.is_err(), "missing auth should be rejected");' + $crlf + "        assert_eq!(res.unwrap_err().0, StatusCode::UNAUTHORIZED);" + $crlf + "    }" + $crlf + $crlf + "}"
if ($s.Contains($old4)) { $s = $s.Replace($old4, $new4); Write-Host "4 TESTS OK" } else { Write-Host "4 TESTS FAIL" }

[IO.File]::WriteAllText($f, $s)
Write-Host "Final lines:" ($s.Split("`n").Count)
