$f = 'd:\by\polap-db\services\voltnuerongridd\src\main.rs'
$s = [IO.File]::ReadAllText($f)
$crlf = "`r`n"

# 1. Insert structs after WalFlushCountResponse
$old = "struct WalFlushCountResponse {${crlf}    status: &'static str,${crlf}    flush_count: usize,${crlf}}${crlf}${crlf}// " + [char]0x2500 + [char]0x2500 + [char]0x2500 + " S7-WS6-04"
$new = "struct WalFlushCountResponse {${crlf}    status: &'static str,${crlf}    flush_count: usize,${crlf}}${crlf}${crlf}// " + [char]0x2500 + [char]0x2500 + [char]0x2500 + " S3-WS1-28: rows/field/count + wal/entry/latest structs " + ([char]0x2500 * 17) + "${crlf}${crlf}#[derive(Debug, Serialize)]${crlf}struct RowsFieldCountResponse {${crlf}    status: &'static str,${crlf}    total_fields: usize,${crlf}    row_count: usize,${crlf}}${crlf}${crlf}#[derive(Debug, Serialize)]${crlf}struct WalEntryLatestResponse {${crlf}    status: &'static str,${crlf}    has_entry: bool,${crlf}    entry_sequence: u64,${crlf}}${crlf}${crlf}// " + [char]0x2500 + [char]0x2500 + [char]0x2500 + " S7-WS6-04"
if ($s.Contains($old)) { $s = $s.Replace($old, $new); Write-Host "1 STRUCT OK" } else { Write-Host "1 STRUCT FAIL"; $s.Substring($s.IndexOf('WalFlushCountResponse')-5, 200) }

# 2. Insert routes after wal/flush/count
$old2 = '        .route("/api/v1/store/wal/flush/count", get(wal_flush_count))' + $crlf + '        // S11-WS1-19'
$new2 = '        .route("/api/v1/store/wal/flush/count", get(wal_flush_count))' + $crlf + '        // S3-WS1-28: rows/field/count + wal/entry/latest' + $crlf + '        .route("/api/v1/store/rows/field/count", get(rows_field_count))' + $crlf + '        .route("/api/v1/store/wal/entry/latest", get(wal_entry_latest))' + $crlf + '        // S11-WS1-19'
if ($s.Contains($old2)) { $s = $s.Replace($old2, $new2); Write-Host "2 ROUTES OK" } else { Write-Host "2 ROUTES FAIL" }

# 3. Insert handlers before S7-WS6-01
$raftAnchor = '// ' + [char]0x2500 + [char]0x2500 + [char]0x2500 + ' S7-WS6-01: Raft vote statistics endpoint'
$handlerBlock = '// ' + [char]0x2500 + [char]0x2500 + [char]0x2500 + ' S3-WS1-28: rows/field/count endpoint ' + ([char]0x2500 * 34) + $crlf + 'async fn rows_field_count(' + $crlf + '    State(state): State<Arc<AppState>>,' + $crlf + '    headers: HeaderMap,' + $crlf + ') -> Result<Json<RowsFieldCountResponse>, (StatusCode, Json<AuthErrorResponse>)> {' + $crlf + '    require_operator_auth(&headers, &state)?;' + $crlf + '    let snapshot = state.row_store.lock().expect("row_store lock rows_field_count").export_rows_snapshot();' + $crlf + '    let row_count = snapshot.len();' + $crlf + '    let total_fields = snapshot.values().map(|r| r.len()).sum::<usize>();' + $crlf + '    Ok(Json(RowsFieldCountResponse { status: "ok", total_fields, row_count }))' + $crlf + '}' + $crlf + $crlf + '// ' + [char]0x2500 + [char]0x2500 + [char]0x2500 + ' S3-WS1-28: wal/entry/latest endpoint ' + ([char]0x2500 * 35) + $crlf + 'async fn wal_entry_latest(' + $crlf + '    State(state): State<Arc<AppState>>,' + $crlf + '    headers: HeaderMap,' + $crlf + ') -> Result<Json<WalEntryLatestResponse>, (StatusCode, Json<AuthErrorResponse>)> {' + $crlf + '    require_operator_auth(&headers, &state)?;' + $crlf + '    let records = state.wal_engine.lock().expect("wal_engine lock wal_entry_latest").wal_records();' + $crlf + '    let entry_sequence = records.last().map(|r| r.sequence).unwrap_or(0);' + $crlf + '    let has_entry = !records.is_empty();' + $crlf + '    Ok(Json(WalEntryLatestResponse { status: "ok", has_entry, entry_sequence }))' + $crlf + '}' + $crlf + $crlf + $raftAnchor
if ($s.Contains($raftAnchor)) { $s = $s.Replace($raftAnchor, $handlerBlock); Write-Host "3 HANDLERS OK" } else { Write-Host "3 HANDLERS FAIL" }

# 4. Tests: insert before final closing brace
$lastTest = '        assert!(result.is_err());' + $crlf + '        assert_eq!(result.unwrap_err().0, StatusCode::UNAUTHORIZED);' + $crlf + '    }' + $crlf + $crlf + '}'
$newTests = '        assert!(result.is_err());' + $crlf + '        assert_eq!(result.unwrap_err().0, StatusCode::UNAUTHORIZED);' + $crlf + '    }' + $crlf + $crlf + '    // ' + ([char]0x2500 * 2) + ' S3-WS1-28: rows_field_count tests ' + ([char]0x2500 * 38) + $crlf + $crlf + '    #[tokio::test]' + $crlf + '    async fn s11_ws1_28_rows_field_count_ok() {' + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = operator_headers("test-key", "admin");' + $crlf + '        let res = rows_field_count(State(state), hdrs).await;' + $crlf + '        assert!(res.is_ok(), "rows_field_count should return ok");' + $crlf + '        let body = res.unwrap().0;' + $crlf + '        assert_eq!(body.status, "ok");' + $crlf + '    }' + $crlf + $crlf + '    #[tokio::test]' + $crlf + '    async fn s11_ws1_28_rows_field_count_missing_auth() {' + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = HeaderMap::new();' + $crlf + '        let res = rows_field_count(State(state), hdrs).await;' + $crlf + '        assert!(res.is_err(), "missing auth should be rejected");' + $crlf + '        assert_eq!(res.unwrap_err().0, StatusCode::UNAUTHORIZED);' + $crlf + '    }' + $crlf + $crlf + '    // ' + ([char]0x2500 * 2) + ' S3-WS1-28: wal_entry_latest tests ' + ([char]0x2500 * 38) + $crlf + $crlf + '    #[tokio::test]' + $crlf + '    async fn s11_ws1_28_wal_entry_latest_ok() {' + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = operator_headers("test-key", "admin");' + $crlf + '        let res = wal_entry_latest(State(state), hdrs).await;' + $crlf + '        assert!(res.is_ok(), "wal_entry_latest should return ok");' + $crlf + '        let body = res.unwrap().0;' + $crlf + '        assert_eq!(body.status, "ok");' + $crlf + '    }' + $crlf + $crlf + '    #[tokio::test]' + $crlf + '    async fn s11_ws1_28_wal_entry_latest_missing_auth() {' + $crlf + '        let state = state_with_key(Some("test-key"));' + $crlf + '        let hdrs = HeaderMap::new();' + $crlf + '        let res = wal_entry_latest(State(state), hdrs).await;' + $crlf + '        assert!(res.is_err(), "missing auth should be rejected");' + $crlf + '        assert_eq!(res.unwrap_err().0, StatusCode::UNAUTHORIZED);' + $crlf + '    }' + $crlf + $crlf + '}'
if ($s.Contains($lastTest)) { $s = $s.Replace($lastTest, $newTests); Write-Host "4 TESTS OK" } else { Write-Host "4 TESTS FAIL" }

[IO.File]::WriteAllText($f, $s)
Write-Host "Lines:" ($s.Split("`n").Count)
