/**
 * voltnuerongrid.h — C header for the VoltNueronGrid driver C FFI layer.
 *
 * This is the hand-written reference header.  In a production build, the
 * canonical version is generated by `cbindgen` from `src/lib.rs`.
 *
 * Build the shared/static library:
 *   cargo build --release -p vng-driver-c
 *
 * Link against:
 *   target/release/libvoltnuerongrid_driver.so  (Linux/macOS)
 *   target/release/voltnuerongrid_driver.dll    (Windows)
 *   target/release/libvoltnuerongrid_driver.a   (staticlib)
 */

#ifndef VOLTNUERONGRID_H
#define VOLTNUERONGRID_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Opaque driver handle
 * ---------------------------------------------------------------------- */

/**
 * Opaque handle representing an initialised driver instance.
 * Allocate with vng_driver_create(); release with vng_driver_free().
 */
typedef struct VngDriverHandle VngDriverHandle;

/* -------------------------------------------------------------------------
 * Request structure
 * ---------------------------------------------------------------------- */

/**
 * A built HTTP request, filled in by the request-builder functions.
 *
 * String fields are heap-allocated by the library.  The caller must release
 * them by calling vng_request_free() once the request has been dispatched.
 *
 * method:       0 = GET, 1 = POST
 * url:          null-terminated full URL string
 * headers_json: null-terminated JSON object of request headers
 * body_json:    null-terminated JSON body, or NULL for GET requests
 */
typedef struct {
    int    method;
    char*  url;
    char*  headers_json;
    char*  body_json;
} VngRequest;

/* -------------------------------------------------------------------------
 * Driver lifecycle
 * ---------------------------------------------------------------------- */

/**
 * Creates a new driver handle.
 *
 * @param base_url   Base HTTP URL, e.g. "http://localhost:8080"
 * @param session_id Session identifier for multiplexing
 * @param mode       Operating mode: "admin", "operator", or "tenant"
 * @return           Opaque handle, or NULL on failure
 *
 * The returned handle must be freed with vng_driver_free().
 */
VngDriverHandle* vng_driver_create(
    const char* base_url,
    const char* session_id,
    const char* mode
);

/**
 * Frees a driver handle.
 *
 * @param handle  Handle returned by vng_driver_create(); NULL is a no-op.
 */
void vng_driver_free(VngDriverHandle* handle);

/* -------------------------------------------------------------------------
 * Request builders
 * ---------------------------------------------------------------------- */

/**
 * Builds a GET /health request.
 *
 * @param handle  Valid non-null driver handle
 * @param out     Pointer to a VngRequest struct to fill in (caller-owned)
 * @return        0 on success, non-zero on error
 *
 * The caller must call vng_request_free(out) after use.
 */
int vng_driver_build_health_request(
    const VngDriverHandle* handle,
    VngRequest*            out
);

/**
 * Builds a POST /api/v1/sql/execute request.
 *
 * @param handle     Valid non-null driver handle
 * @param sql_batch  SQL text to execute (null-terminated)
 * @param out        Pointer to a VngRequest struct to fill in
 * @return           0 on success, non-zero on error
 *
 * The caller must call vng_request_free(out) after use.
 */
int vng_driver_build_sql_execute_request(
    const VngDriverHandle* handle,
    const char*            sql_batch,
    VngRequest*            out
);

/* -------------------------------------------------------------------------
 * Resource cleanup
 * ---------------------------------------------------------------------- */

/**
 * Frees heap-allocated strings inside a VngRequest.
 *
 * Does NOT free the VngRequest struct itself (if it is stack-allocated by
 * the caller, no separate free is needed).
 *
 * @param req  Pointer to the request whose string fields should be freed.
 *             NULL is a no-op.
 */
void vng_request_free(VngRequest* req);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* VOLTNUERONGRID_H */
